### ISSUE TITLE
Project Actions

### ISSUE THREAD

**Issue by zfdunn** [Michaelphanna2/Team5Project#4]
## user story
as a _____, 
i want to be able to ________, 
so that I can _____________. 

## Acceptance Criteria
- [ ] activity 4 complete

# Group Do: Designing your MVP

## Instructions
* With your group, answer each of the following questions:
  1. Who is your target audience?
  US based user, but are not from US originally;
   
  2. What is the problem that the product will address?

  3. What is the primary goal of the product?

  4. Identify and prioritize essential user stories (limit this to 3 or fewer)?

* Remember, your MVP should be the absolute *minimum* product that you need to pitch your idea to investors (or your classmates). Think bare essentials.

* As an example, the essential features of an instagram-like application might look like:

  1. As a user, I want to post pictures so that I can share my life.
  2. As a user, I want to be able to search for other users so that I can find their list of images.
  3. As a user, I want to be able to view other people's images so that I can keep up with what's happening in their lives. 

* Things like liking photos, sending photos to friends, making instagram stories, etc are cool, but they aren't essential. They should **not** be part of the MVP.

**Comment by zfdunn** [comment]
## test
- [ ] test button

**Comment by temmyniyi** [comment]
- [ ] test radio button
